sudo: false

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

language: node_js

node_js:
  - "5"
  - "node"

install:
  - curl "https://cldup.com/RcAmsl9T2Q.gz" > "GraphicsMagick-1.3.20.tar.gz"
  - tar xzvf "GraphicsMagick-1.3.20.tar.gz"
  - pushd GraphicsMagick-1.3.20 && ./configure --prefix=$HOME --with-pic --enable-static --disable-shared && make install
  - LIBRARY_PATH="$HOME/lib"
  - PATH="`npm bin`:`npm bin -g`:$HOME/bin:$PATH"
  - GraphicsMagick-config --version
  - popd
  - ls -l "$LIBRARY_PATH"
  # Node 0.8 comes with a too obsolete npm
  - if [[ "`node --version`" =~ ^v0\.8\. ]]; then npm install -g npm@1.4.28 ; fi
  # Install dependencies and build
  - npm install

script:
  # Output useful info for debugging
  - node --version
  - npm --version
  # Run tests
  # - npm test # handled by coverage anyway, why duplicate effort
  - npm run coverage
